step_2/geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp

urlpatterns = [

    path('', mainapp.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    #
    # path('products/all/', mainapp.products, name='products_all'),
    # path('products/home/', mainapp.products, name='products_home'),
    # path('products/office/', mainapp.products, name='products_office'),
    # path('products/modern/', mainapp.products, name='products_modern'),
    # path('products/classic/', mainapp.products, name='products_classic'),

    path('contacts/', mainapp.contacts, name='contacts'),
    path('admin/', admin.site.urls),

]
# print(path('products/', mainapp.products))
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

step_2/geekshop/mainapp/urls.py
from django.urls import path
from mainapp.views import products, products_list
from mainapp.apps import MainappConfig

app_name = 'products'
# app_name = MainappConfig.name

urlpatterns = [
    path('', products, name='products_hot_product'),
    path('<int:pk>', products_list, name='products_list'),

]

step_2/geekshop/mainapp/models.py
# from tabnanny import verbose
from django.db import models


# from django.db.models import CharField


class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='Название', unique=True)
    description = models.TextField(verbose_name='Описание')

    # class ProductCategory(models.Model):
    #     name: CharField = models.CharField(verbose_name='имя', max_length=64, unique=True)
    #     description = models.TextField(verbose_name='Описание', blank=True)

    def __str__(self):
        return f'#{self.pk}.{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категория'
        ordering = ('name', )

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    image=models.ImageField(upload_to='product', blank=True, null=True)
    name = models.CharField(max_length=128, verbose_name='Название')
    short_desk = models.CharField(max_length=128, verbose_name='Краткое описание')
    description = models.TextField(verbose_name='Описание')
    price= models.DecimalField(max_digits=8, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    def __str__(self):
        return f'{self.name} ({self.category.name})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

step_2/geekshop/mainapp/views.py
from django.shortcuts import render
from mainapp.models import Product, Category


# Create your views here.
def index(request):
     context = {
         'products': Product.objects.all()[:4]
     }
     return render(request, 'mainapp/index.html', context)



#
#
# def products(request):
#     return render(request, 'mainapp/products.html')
#
#
# def contacts(request):
#     return render(request, 'mainapp/contacts.html')

# def index(request):
#         return render(request, 'mainapp/index.html')


def products(request):

    # links_menu = [
    #     {'href': 'products_all', 'title': 'все'},
    #     {'href': 'products_home', 'title': 'дом'},
    #     {'href': 'products_office', 'title': 'офис'},
    #     {'href': 'products_modern', 'title': 'модерн'},
    #     {'href': 'products_classic', 'title': 'классика'},
    #
    # ]
    context = {
        'links_menu': Category.objects.all()
    }
    return render(request, 'mainapp/products.html', context)

def products_list(request, pk):
    context = {'links_menu': Category.objects.all()
    }
    return render(request, 'mainapp/products.html', context)


def contacts(request):
    return render(request, 'mainapp/contacts.html')

# context = {
    #     'keys_list': [
    #         {
    #             'key1': 'value1',
    #             'key2': 'value2',
    #             'key3': 'value3',
    #         },
    #         {
    #             'key1': 'value10',
    #             'key2': 'value20',
    #             'key3': 'value30',
    #         }
    #     ]
    # }

step_2/geekshop/mainapp/templates/mainapp/Base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>{{title|default:"Мой магазин"}}</title>
	{% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
	{% endblock %}

	{% block js %}
	{% endblock %}

</head>
<body>
	<div class="container">

		{% block menu %}
		{% endblock %}

		{% block content %}
		{% endblock %}

		<div class="clr"></div>

	</div>

    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now 'M' %} {% now 'Y' %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>

</body>
</html>

step_2/geekshop/mainapp/templates/mainapp/contacts.html
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
<!--	<meta charset="utf-8">-->
<!--	<title>Контакты</title>-->
<!--	<link rel="stylesheet" type="text/css" href="/static/style.css">-->
<!--	<link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">-->
<!--</head>-->
<!--<body>-->
<!--	<div class="container">-->
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
		<div class="hero">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
			<h1>наши контакты</h1>
		</div>
{% endblock %}

{% block content %}
		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
{% endblock %}

step_2/geekshop/mainapp/templates/mainapp/includes/inc_main_menu.html
<a href="{% url 'index' %}" class="logo"></a>

<ul class="menu">
	<li><a href="{% url 'index' %}" {% if request.resolver_match.url_name == 'index' %} class="active"{% endif %}>домой</a></li>
	<li><a href="{% url 'products:products_hot_product' %}" {% if request.resolver_match.url_name == 'products' %} class="active"{% endif %}>продукты</a></li>
	<li><a href="{% url 'contacts' %}" {% if request.resolver_match.url_name == 'contacts' %} class="active"{% endif %}>контакты</a></li>

</ul>
<a href="#" class="search"></a>
<a href="#" class="basket"></a>

step_2/geekshop/mainapp/templates/mainapp/includes/inc_products_menu.html
<ul class="links-menu">
	<li>
			<a href="{% url 'products:products_list' 0 %}">
			   все
			</a>

		</li>
	{% for link_menu in links_menu %}



		<li>
			<a href="{% url 'products:products_list' link_menu.pk %}" {% if request.resolver_match_url_name == link_menu.href %}class="active"{% endif %}>
			   {{ link_menu.name }}
			</a>

		</li>
	{% endfor %}
<!--					<li><a href="#" class="active">все</a></li>-->
<!--					<li><a href="#">дом</a></li>-->
<!--					<li><a href="#">офис</a></li>-->
<!--					<li><a href="#">модерн</a></li>-->
<!--					<li><a href="#">классика</a></li>-->
</ul>
{{ links_menu }}

step_2/geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}

		<div class="slider">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}

			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
{% endblock %}



{% block content %}
		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				<div class="block">
					<a href="#"><img src="{% static 'img/product-1.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>Отличный стул</h4>
							<p>Расположитесь комфортно. </p>
						</div> 
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>	
			</div>
		</div>
{% endblock %}
		<div class="clr"></div>

<!--	</div>-->

<!--    <div class="footer">-->
<!--        <div class="clearfix">-->
<!--            <div class="text-footer">-->
<!--                <h3>контакты</h3>-->
<!--            </div>-->
<!--            <div class="text-footer">-->
<!--                <h3>полезная информация</h3>-->
<!--            </div>-->
<!--            <div class="text-footer clearfix">-->
<!--                <h3>Оставайтесь на связи</h3>-->
<!--                <p>Подписаться на новости и рассылки</p>-->
<!--                <form>-->
<!--                    <input type="email" name="email" placeholder="ваш email">-->
<!--                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>-->
<!--                </form>-->
<!--            </div>-->
<!--        </div>-->
<!--        <p class="small">&copy; GB {% now 'M' %} {% now 'Y' %}</p>-->
<!--        <div class="social">-->
<!--            <a href="#" class="social1"></a>-->
<!--            <a href="#" class="social2"></a>-->
<!--            <a href="#" class="social3"></a>-->
<!--            <a href="#" class="social4"></a>-->
<!--        </div>-->
<!--        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>-->
<!--    </div>	-->
<!--	-->
<!--</body>-->
<!--</html>-->

step_2/geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
<!--<!DOCTYPE html>-->
<!--<html>-->
<!--<head>-->
<!--	<meta charset="utf-8">-->
<!--	<title>Каталог</title>-->
<!--	<link rel="stylesheet" href="/static/style.css">-->
<!--	<link rel="stylesheet" href="/static/fonts/font-awesome/css/font-awesome.css">-->
<!--</head>-->
<body>
	<div class="container">
		<div class="hero-white">
			<div class="header clearfix">
				{% include 'mainapp/includes/inc_main_menu.html' %}
			</div>
		</div>
{% endblock %}

{% block content %}
		<div class="details">
			<div class="links clearfix">
<!--				{{ links_menu }}-->
				{% include 'mainapp/includes/inc_products_menu.html' %}
<!--				{% include 'mainapp/includes/inc_main_menu.html' %}-->
<!--				<ul class="links-menu">-->
<!--					<li><a href="#" class="active">все</a></li>-->
<!--					<li><a href="#">дом</a></li>-->
<!--					<li><a href="#">офис</a></li>-->
<!--					<li><a href="#">модерн</a></li>-->
<!--					<li><a href="#">классика</a></li>-->
<!--				</ul>-->
			</div>
		</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/static/img/slider1.jpg">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="/static/img/controll.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/static/img/controll1.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/static/img/controll2.jpg" alt="">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">Отличный стул</h3>
					<h3 class="red">горячее предложение</h3>
					<p class="price"> 2585.9 <span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>
					<div class="description-text">
						<p>Расположитесь комфортно.</p> 
						<p>Отличное качество материалов
						позволит вам это.</p> 
						<p>Различные цвета</p>
						<p>высочайший уровень
						эргономики и прочность.</p>
					</div>
				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
				</div>
				<div class="related-products clearfix">
					<div class="block">
						<a href="#"><img src="/static/img/product-11.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-21.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>
					<div class="block">
						<a href="#"><img src="/static/img/product-31.jpg" alt="">
							<div class="text">
								<img src="/static/img/icon-hover.png" alt="img">
								<h4>Стул повышенного качества</h4>
								<p>Не оторваться. </p>
							</div>
						</a>
					</div>

				</div>
			</div>
		</div>
{% endblock %}